"""add expo_push_token and batch_notification_logs

Revision ID: 277c78f01a61
Revises: 8132b4f16ace
Create Date: 2026-05-29 19:41:40.239063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '277c78f01a61'
down_revision: Union[str, None] = '8132b4f16ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_notification_logs_batch_id'), 'batch_notification_logs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batch_notification_logs_id'), 'batch_notification_logs', ['id'], unique=False)
    op.create_index(op.f('ix_batch_notification_logs_user_id'), 'batch_notification_logs', ['user_id'], unique=False)
    op.add_column('users', sa.Column('expo_push_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'expo_push_token')
    op.drop_index(op.f('ix_batch_notification_logs_user_id'), table_name='batch_notification_logs')
    op.drop_index(op.f('ix_batch_notification_logs_id'), table_name='batch_notification_logs')
    op.drop_index(op.f('ix_batch_notification_logs_batch_id'), table_name='batch_notification_logs')
    op.drop_table('batch_notification_logs')
    # ### end Alembic commands ###
