"""add offer_reminder_sent to tankers

Revision ID: 5d2e134bf1aa
Revises: e0e2c6fcc61a
Create Date: 2026-06-18 14:30:16.666074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2e134bf1aa'
down_revision: Union[str, None] = 'e0e2c6fcc61a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tankers',
        sa.Column('offer_reminder_sent', sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tankers', 'offer_reminder_sent')
    # ### end Alembic commands ###
