"""add_driver_offline_tracking_fields_to_tanker

Revision ID: 64feeac4ad49
Revises: cb20e9916ce4
Create Date: 2026-06-01 08:18:49.468600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64feeac4ad49'
down_revision: Union[str, None] = 'cb20e9916ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tankers', sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True))
    op.add_column('tankers', sa.Column('offline_grace_started_at', sa.DateTime(), nullable=True))
    op.add_column('tankers', sa.Column('offline_notified_at', sa.DateTime(), nullable=True))
    op.add_column('tankers', sa.Column('offline_escalated_at', sa.DateTime(), nullable=True))
    op.add_column('tankers', sa.Column('offline_followup_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tankers', 'offline_followup_sent_at')
    op.drop_column('tankers', 'offline_escalated_at')
    op.drop_column('tankers', 'offline_notified_at')
    op.drop_column('tankers', 'offline_grace_started_at')
    op.drop_column('tankers', 'last_heartbeat_at')
    # ### end Alembic commands ###
