"""add fleet_number to tankers

Revision ID: 8132b4f16ace
Revises: 9f5499991eb5
Create Date: 2026-05-28 22:45:13.615561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8132b4f16ace'
down_revision: Union[str, None] = '9f5499991eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tankers', sa.Column('fleet_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tankers', 'fleet_number')
    # ### end Alembic commands ###
