"""add terrain_elevation_m to customer_site_profiles

Revision ID: 911bce4277c5
Revises: 6d21c21ab2f2
Create Date: 2026-06-14 21:52:05.724193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '911bce4277c5'
down_revision: Union[str, None] = '6d21c21ab2f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.add_column('customer_site_profiles', sa.Column('terrain_elevation_m', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_site_profiles', 'terrain_elevation_m')
    op.create_table('notification_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('actor_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_preferences_pkey')),
    sa.UniqueConstraint('actor_type', 'actor_id', name=op.f('uq_notif_pref_actor'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
    # ### end Alembic commands ###
