"""add customer site profiles

Revision ID: 9f5499991eb5
Revises: ebcac426228e
Create Date: 2026-05-28 12:24:39.690078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5499991eb5'
down_revision: Union[str, None] = 'ebcac426228e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_site_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('landmark_notes', sa.String(), nullable=True),
    sa.Column('tank_capacity_liters', sa.Integer(), nullable=True),
    sa.Column('tank_height_m', sa.Float(), nullable=True),
    sa.Column('hose_distance_m', sa.Float(), nullable=True),
    sa.Column('road_difficulty', sa.Integer(), nullable=False),
    sa.Column('parking_difficulty', sa.Integer(), nullable=False),
    sa.Column('has_gate', sa.Boolean(), nullable=False),
    sa.Column('gate_notes', sa.String(), nullable=True),
    sa.Column('delivery_count', sa.Integer(), nullable=False),
    sa.Column('avg_delivery_duration_minutes', sa.Float(), nullable=True),
    sa.Column('pump_stress_count', sa.Integer(), nullable=False),
    sa.Column('rejection_count', sa.Integer(), nullable=False),
    sa.Column('incident_count', sa.Integer(), nullable=False),
    sa.Column('dispute_count', sa.Integer(), nullable=False),
    sa.Column('anomaly_count', sa.Integer(), nullable=False),
    sa.Column('truthfulness_score', sa.Float(), nullable=False),
    sa.Column('cooperation_score', sa.Float(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('driver_verified_tank_height_m', sa.Float(), nullable=True),
    sa.Column('driver_verified_hose_distance_m', sa.Float(), nullable=True),
    sa.Column('driver_verified_road_difficulty', sa.Integer(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_site_profiles_id'), 'customer_site_profiles', ['id'], unique=False)
    op.add_column('delivery_records', sa.Column('site_profile_id', sa.Integer(), nullable=True))
    op.add_column('delivery_records', sa.Column('driver_reported_tank_height_m', sa.Float(), nullable=True))
    op.add_column('delivery_records', sa.Column('driver_reported_hose_distance_m', sa.Float(), nullable=True))
    op.add_column('delivery_records', sa.Column('driver_reported_road_difficulty', sa.Integer(), nullable=True))
    op.add_column('delivery_records', sa.Column('site_conditions_match', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'delivery_records', 'customer_site_profiles', ['site_profile_id'], ['id'])
    op.add_column('requests', sa.Column('site_profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'requests', 'customer_site_profiles', ['site_profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_column('requests', 'site_profile_id')
    op.drop_constraint(None, 'delivery_records', type_='foreignkey')
    op.drop_column('delivery_records', 'site_conditions_match')
    op.drop_column('delivery_records', 'driver_reported_road_difficulty')
    op.drop_column('delivery_records', 'driver_reported_hose_distance_m')
    op.drop_column('delivery_records', 'driver_reported_tank_height_m')
    op.drop_column('delivery_records', 'site_profile_id')
    op.drop_index(op.f('ix_customer_site_profiles_id'), table_name='customer_site_profiles')
    op.drop_table('customer_site_profiles')
    # ### end Alembic commands ###
