"""add is_verified to tankers and admin_users

Revision ID: a1e2b9d9a399
Revises: b8f2c4d6e9a1
Create Date: 2026-07-19 16:36:08.523997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e2b9d9a399'
down_revision: Union[str, None] = 'b8f2c4d6e9a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('tankers', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tankers', 'is_verified')
    op.drop_column('admin_users', 'is_verified')
    # ### end Alembic commands ###
