"""add hubs table and hub_id columns

Revision ID: ad0f3accd208
Revises: d75d01b382e6
Create Date: 2026-07-12 19:34:17.070228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad0f3accd208'
down_revision: Union[str, None] = 'd75d01b382e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_hubs_id'), 'hubs', ['id'], unique=False)
    op.add_column('admin_users', sa.Column('hub_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'admin_users', 'hubs', ['hub_id'], ['id'])
    op.add_column('batches', sa.Column('hub_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'batches', 'hubs', ['hub_id'], ['id'])
    op.add_column('requests', sa.Column('hub_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'requests', 'hubs', ['hub_id'], ['id'])
    op.add_column('tankers', sa.Column('hub_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tankers', 'hubs', ['hub_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tankers', type_='foreignkey')
    op.drop_column('tankers', 'hub_id')
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_column('requests', 'hub_id')
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.drop_column('batches', 'hub_id')
    op.drop_constraint(None, 'admin_users', type_='foreignkey')
    op.drop_column('admin_users', 'hub_id')
    op.drop_index(op.f('ix_hubs_id'), table_name='hubs')
    op.drop_table('hubs')
    # ### end Alembic commands ###
