"""add_abandoned_delivery_count_to_driver_metric

Revision ID: c759750cde87
Revises: 64feeac4ad49
Create Date: 2026-06-01 08:20:30.730420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c759750cde87'
down_revision: Union[str, None] = '64feeac4ad49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_metrics', sa.Column('abandoned_delivery_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_metrics', 'abandoned_delivery_count')
    # ### end Alembic commands ###
