"""add_queued_at_to_batches_and_requests

Revision ID: d75d01b382e6
Revises: 5d2e134bf1aa
Create Date: 2026-07-12 17:34:54.100860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd75d01b382e6'
down_revision: Union[str, None] = '5d2e134bf1aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('queued_at', sa.DateTime(), nullable=True))
    op.add_column('requests', sa.Column('queued_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'queued_at')
    op.drop_column('batches', 'queued_at')
    # ### end Alembic commands ###
